#GET http://localhost:4004/odata/v4/product/printhelloworld(input='Hello')

#GET http://localhost:4004/odata/v4/product/addition(num1=5, num2=3)



#GET http://localhost:4004/rest/product/MyFunction(category=1)

#Product
#GET http://localhost:4004/odata/v4/proyect1/Product

#Supplier
#GET http://localhost:4004/odata/v4/proyect1/Supplier

#Añadir carro
#POST http://localhost:4004/odata/v4/proyect1/Product 
#Content-Type: application/json

#{
  # "emission": 232344,
   #"rating": 4.5,
  # "name": "Toyota",
   #"category": 1,
   #"cost_price": 20000,
   #"cost_stock": 5
#}
##ejemplo de asociacion
#GET http://localhost:4004/odata/v4/proyect1/Product?$expand=supplier&$select=name,category

#GET http://localhost:4004/odata/v4/proyect1/Product?$expand=conversation 

#GET http://localhost:4004/odata/v4/proyect1/MyFunction(name='John Doe')
#POST http://localhost:4004/odata/v4/proyect1/MyAction
#Content-Type: application/json

#{
 # "name": "Luis Morin"
#}