/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ProductObjectPageObjectPage journey");

        opaTest("Navigate to ProductObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheProductList.onFilterBar().iExecuteSearch();

            Then.onTheProductList.onTable().iCheckRows();
            When.onTheProductList.onTable().iPressRow(0);

            Then.onTheProductObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheProductObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheProductObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ID" });
            Then.onTheProductObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "name" });
            Then.onTheProductObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "stock" });
            Then.onTheProductObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "price" });
            Then.onTheProductObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "category" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});